version: '3.4'

services:
  cppengine:
    image: cppengine
    build:
      context: .
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      DISPLAY: ${DISPLAY}
